### ISSUE TITLE
JavaScript order in config.yml

### ISSUE THREAD

**Issue by pablopaul** [ZeelandFamily/zf-theme#11]
It can be the case that particular Foundation libraries are not included in the right order in the [config.yaml](https://github.com/ZeelandFamily/zf-theme/blob/master/config.yml#L47) since it seems like the order in the `zf-theme` config is made up from alphabetical order which does not necessarily fulfill dependency needs from a any used Foundation library. You can find the dependencies for each Foundation JS library on the according doc page and then you can check the order in the `config.yml`. Dependencies must be loaded before the library loads which needs the dependency. Issue originally came up here https://github.com/zurb/foundation-sites/issues/10502

**Comment by danielck** [comment]
@pablopaul So is this still an issue or was the real issue #10 ?

**Comment by pablopaul** [comment]
@danielck it could be still in issue for other components which has different/other dependencies then Magellan.

**Comment by danielck** [comment]
This should no longer be an issue since I've updated the theme to use the webpack config from upstream, so dependencies should be properly fulfilled.
