### ISSUE TITLE
Styles disappears after page reload

### ISSUE THREAD

**Issue by veerap000** [ZeelandFamily/zf-theme#13]
Sass files that are imported in app.scss disappears after page reload.

**Comment by veerap000** [comment]
Something todo with browser cache. Need to use some unique timestamp version when working in dev mode.

**Comment by danielck** [comment]
Could not repeat this. Can you still confirm @veerap000 that this is an issue with current zf-theme?

**Comment by veerap000** [comment]
I haven't got this problem for awhile, closing this.
