### ISSUE TITLE
Add Foundation 6.4 compatibility

### ISSUE THREAD

**Issue by danielck** [ZeelandFamily/zf-theme#5]
Things to consider: Do we add the new XY grid by default? We don't have any default grid classes in the markup anyway currently so we might as well.

**Comment by pablopaul** [comment]
@danielck I would suggest to add XY grid by default, since this is the new standard which Zurb Foundation populates, the theme should follow the suggestion. And if it does not have any grid markup, the decision is easy, or? 👍

**Comment by pablopaul** [comment]
@danielck a upgrade PR to Foundation Sites 6.4.1 is waiting here #8

**Comment by danielck** [comment]
Merged in https://github.com/ZeelandFamily/zf-theme/commit/f40555a1628e3aca7f1b159aa41b72e5fe47b336

Big thanks for your contribution @pablopaul.

**Comment by danielck** [comment]
I noticed the XY grid was actually not being included, so updated in latest commit: https://github.com/ZeelandFamily/zf-theme/commit/873dc558034ea19182370cd88174baea5c8ce7a9
