### ISSUE TITLE
Page builder to use with zf-theme

### ISSUE THREAD

**Issue by pablopaul** [ZeelandFamily/zf-theme#7]
@danielck can you recommend a page builder which works with zf-theme and outputs Zurb Foundation markup?

**Comment by danielck** [comment]
@pablopaul sorry I don't have any recommendations for this. We try to avoid page builders whenever we can so looking for one is not really on our list or priorities at Zeeland. :) One that adds Foundation markup without adding any styles / JS of its own would certainly be interesting though and might come in handy in some special cases. Usually though we feel it is better to keep a clear separation of content and structure.

**Comment by pablopaul** [comment]
@danielck All right, some people use ACF to have 100% control over the outputed markup. In a smaller project I customized Site Origins Page Builder to output Foundation markup, worked quite good. In the next project I am going to use the ACF approach 👍
